### ISSUE TITLE
[Off-Topic] Best Compression settings in Inno Setup Compiler

### ISSUE THREAD

**Issue by abuhenasobuj** [martinprikryl/test#1]
Sir, I read this [Best Compression settings in Inno Setup Compiler](http://stackoverflow.com/questions/40447498/best-compression-settings-in-inno-setup-compiler
) post on **StackOverflow**.

Can you tell me which (_setup builder_) software screenshot you attached in your post?

**Comment by martinprikryl** [comment]
There's no screenshot in my post. If you mean the question, it's obsolete ISTools.

**Comment by abuhenasobuj** [comment]
Which version `ISTools`? For `Windows OS`?
I didn't seen the interface before this!
